// Sens francais ecrits a la main pour les mots les plus frequents du corpus.
//
// JMdict ne traduit en francais que 26 % des entrees exactes, et pour les particules
// et auxiliaires — qui sont justement les plus frequents — ses gloses anglaises sont
// des explications grammaticales, inutilisables telles quelles par un francophone.
// « indicates sentence topic » n'apprend rien ; « marque le theme de la phrase » si.
//
// Ces 150 mots couvrent environ 62 % de toutes les occurrences du corpus.
// La cle est `lemme|lecture`, telle qu'elle figure dans la table `word`.

export const FRENCH = {
  // --- particules et marqueurs ---
  'は|': 'marque le thème de la phrase',
  'を|': 'marque le complément d’objet direct',
  'の|': 'de (appartenance) ; transforme un verbe en nom',
  'が|': 'marque le sujet',
  'に|': 'à, dans, vers — lieu ou moment',
  'か|': 'marque la question',
  'で|': 'à, dans — là où se passe l’action ; au moyen de',
  'と|': 'et (entre deux noms) ; avec ; si',
  'へ|': 'vers, en direction de',
  'も|': 'aussi, également',
  'から|': 'depuis, à partir de ; parce que',
  'よ|': 'insistance, en fin de phrase',
  'ね|': 'n’est-ce pas ? — cherche l’accord',
  'な|': 'interdiction : ne fais pas',
  'より|': 'que (comparaison) ; à partir de',
  'には|': 'à, pour — thème et destination',
  'まで|': 'jusqu’à',
  '迄|まで': 'jusqu’à',
  'のに|': 'bien que, alors que',
  'でも|': 'mais, cependant ; même',
  'なら|': 'si, dans ce cas',

  // --- etre, avoir, faire ---
  'だ|': 'être — forme neutre',
  'です|': 'être — forme polie',
  'である|': 'être — forme écrite',
  'ですか|': 'marque la question polie',
  'では無い|': 'ne pas être',
  '有る|ある': 'être, se trouver — pour les choses',
  '居る|いる': 'être, se trouver — pour les êtres vivants',
  '無い|ない': 'ne pas être, ne pas y avoir',
  '為る|する': 'faire',
  '為れる|': 'être fait — passif de する',
  '成る|なる': 'devenir',
  'になる|': 'devenir',
  '出来る|できる': 'pouvoir, être capable de',
  '事が出来る|': 'pouvoir, être capable de',

  // --- pronoms et demonstratifs ---
  '私|わたし': 'je, moi',
  '私たち|わたしたち': 'nous',
  '我々|': 'nous',
  '彼|かれ': 'il, lui ; petit ami',
  '彼女|かのじょ': 'elle ; petite amie',
  '彼ら|かれら': 'ils, eux',
  '貴方|あなた': 'vous, toi ; chéri(e)',
  '君|きみ': 'tu, toi — familier',
  '自分|じぶん': 'soi-même',
  '此の|この': 'ce, cette — près de moi',
  '其の|その': 'ce, cette — près de toi',
  '彼の|あの': 'ce, cette — loin de nous deux',
  '此れ|これ': 'ceci, ça — près de moi',
  '其れ|それ': 'cela, ça — près de toi',
  '此処|ここ': 'ici',
  '其処|そこ': 'là — près de toi',
  '何処|どこ': 'où',
  '何|なに': 'quoi, que',
  '何か|': 'quelque chose',
  '如何|どう': 'comment',
  'そんな|': 'un tel, de ce genre',
  '皆|みな': 'tous, tout le monde',

  // --- verbes courants ---
  '行く|いく': 'aller',
  '来る|くる': 'venir',
  '見る|みる': 'voir, regarder',
  '見える|みえる': 'être visible, se voir',
  '言う|いう': 'dire',
  '話す|はなす': 'parler',
  '聞く|きく': 'écouter, entendre ; demander',
  '思う|おもう': 'penser, croire',
  '知る|しる': 'savoir, connaître',
  '分かる|わかる': 'comprendre',
  '食べる|たべる': 'manger',
  '読む|': 'lire',
  '書く|かく': 'écrire',
  '買う|かう': 'acheter',
  '持つ|もつ': 'tenir, avoir, porter',
  '置く|おく': 'poser, laisser',
  '住む|すむ': 'habiter, résider',
  '働く|': 'travailler',
  '歩く|': 'marcher',
  '会う|あう': 'rencontrer, voir quelqu’un',
  '教える|': 'enseigner, apprendre à quelqu’un, indiquer',
  '呉れる|くれる': 'donner — vers moi',
  '貰う|もらう': 'recevoir',
  '遣る|やる': 'faire (familier) ; donner',
  '仕舞う|しまう': 'finir, achever ; ranger',
  '入る|はいる': 'entrer',
  '起きる|おきる': 'se lever, se réveiller ; se produire',
  '降る|ふる': 'tomber — pluie, neige',

  // --- formes verbales et auxiliaires ---
  'たい|': 'vouloir faire',
  'ねばならない|': 'devoir, être obligé de',
  '下さい|ください': 's’il vous plaît — donnez-moi, faites',
  '為さい|なさい': 'fais — impératif poli',
  'のです|': 'c’est que… — explication',
  'のだ|': 'c’est que… — explication',
  'だろう|': 'sans doute, probablement',
  'でしょう|': 'sans doute, n’est-ce pas',
  '事がある|': 'il arrive que ; avoir déjà fait',
  '様に|ように': 'comme ; afin que',
  '行けない|': 'il ne faut pas, ce n’est pas bien',

  // --- noms courants ---
  '事|こと': 'chose abstraite, fait',
  '物|もの': 'chose concrète, objet',
  '人|ひと': 'personne, gens',
  '所|ところ': 'endroit, lieu',
  '時|とき': 'moment, quand',
  '時|じ': 'heure — compteur',
  '時間|じかん': 'temps, heure, durée',
  '今|いま': 'maintenant',
  '今日|きょう': 'aujourd’hui',
  '明日|あした': 'demain',
  '昨日|きのう': 'hier',
  '前|ぜん': 'précédent, d’avant',
  '中|なか': 'intérieur, dedans ; parmi',
  '家|いえ': 'maison',
  '部屋|へや': 'chambre, pièce',
  '学校|がっこう': 'école',
  '先生|せんせい': 'professeur, maître',
  '仕事|': 'travail, emploi',
  '勉強|べんきょう': 'étude, travail scolaire',
  '問題|': 'problème, question',
  '手紙|': 'lettre',
  '話|はなし': 'histoire, conversation',
  '本|ほん': 'livre',
  '電話|でんわ': 'téléphone, appel',
  '時計|とけい': 'montre, horloge',
  '車|くるま': 'voiture',
  'バス|': 'bus',
  'お金|': 'argent',
  '水|みず': 'eau',
  '雨|あめ': 'pluie',
  '犬|いぬ': 'chien',
  '父|ちち': 'père — le sien',
  '母|はは': 'mère — la sienne',
  '子供|こども': 'enfant',
  '日本|': 'Japon',
  '英語|えいご': 'anglais — la langue',
  '積もり|': 'intention, projet',
  '本当|ほんとう': 'vérité, vrai',
  '必要|ひつよう': 'nécessaire, besoin',

  // --- adjectifs et adverbes ---
  'いい|': 'bon, bien',
  '良い|よい': 'bon, bien',
  '良く|よく': 'bien ; souvent',
  '悪い|わるい': 'mauvais',
  '好き|すき': 'aimer, apprécier',
  '迚も|とても': 'très',
  '沢山|たくさん': 'beaucoup',
  '少し|': 'un peu',
  '多く|おおく': 'beaucoup, la plupart',
  '全て|すべて': 'tout, la totalité',
  'もう|': 'déjà ; encore',
  '何時も|いつも': 'toujours',

  // --- prefixes ---
  '御|お': 'préfixe de politesse',
  '御|ご': 'préfixe de politesse',
  'に就いて|': 'au sujet de, à propos de'
}
